# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

@typing.final
class AllQueuesFullError(builtins.Exception):
    def __new__(cls, *args: typing.Any) -> AllQueuesFullError: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class Keypair:
    r"""
    Identity keypair of a node.
    """
    @staticmethod
    def generate() -> Keypair:
        r"""
        Generate a new Ed25519 keypair.
        """
    @staticmethod
    def from_bytes(bytes: bytes) -> Keypair:
        r"""
        Construct an Ed25519 keypair from secret key bytes
        """
    def to_bytes(self) -> bytes:
        r"""
        Get the secret key bytes underlying the keypair
        """
    def to_node_id(self) -> builtins.str:
        r"""
        Convert the `Keypair` into the corresponding `PeerId` string, which we use as our `NodeId`.
        """

@typing.final
class MessageTooLargeError(builtins.Exception):
    def __new__(cls, *args: typing.Any) -> MessageTooLargeError: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class NetworkingHandle:
    def __new__(cls, identity: Keypair, bootstrap_peers: typing.Optional[typing.Sequence[builtins.str]] = None, listen_port: builtins.int = 0) -> NetworkingHandle: ...
    async def listen_addresses(self) -> builtins.list[builtins.str]:
        r"""
        Return actual bound listener addresses, including OS-assigned TCP ports.
        """
    async def gossipsub_subscribe(self, topic: builtins.str) -> builtins.bool:
        r"""
        Subscribe to a `GossipSub` topic.

        Returns `True` if the subscription worked. Returns `False` if we were already subscribed.
        """
    async def gossipsub_unsubscribe(self, topic: builtins.str) -> builtins.bool:
        r"""
        Unsubscribes from a `GossipSub` topic.

        Returns `True` if we were subscribed to this topic. Returns `False` if we were not subscribed.
        """
    async def gossipsub_publish(self, topic: builtins.str, data: bytes) -> None:
        r"""
        Publishes a message with multiple topics to the `GossipSub` network.

        If no peers are found that subscribe to this topic, throws `NoPeersSubscribedToTopicError` exception.
        """
    async def recv(self) -> PyFromSwarm: ...

@typing.final
class NoPeersSubscribedToTopicError(builtins.Exception):
    def __new__(cls, *args: typing.Any) -> NoPeersSubscribedToTopicError: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

class PyFromSwarm:
    @typing.final
    class Connection(PyFromSwarm):
        __match_args__ = ("peer_id", "connected", "remote_ip", "remote_tcp_port",)
        @property
        def peer_id(self) -> builtins.str: ...
        @property
        def connected(self) -> builtins.bool: ...
        @property
        def remote_ip(self) -> builtins.str: ...
        @property
        def remote_tcp_port(self) -> builtins.int: ...
        def __new__(cls, peer_id: builtins.str, connected: builtins.bool, remote_ip: builtins.str, remote_tcp_port: builtins.int) -> PyFromSwarm.Connection: ...

    @typing.final
    class Message(PyFromSwarm):
        __match_args__ = ("origin", "topic", "data",)
        @property
        def origin(self) -> builtins.str: ...
        @property
        def topic(self) -> builtins.str: ...
        @property
        def data(self) -> bytes: ...
        def __new__(cls, origin: builtins.str, topic: builtins.str, data: bytes) -> PyFromSwarm.Message: ...

    ...

@typing.final
class ZenohHandle:
    r"""
    Handle to the Zenoh peer session backing the data plane (Phase 1).

    Separate from [`PyNetworkingHandle`] (libp2p): only the DATA topic is routed
    here when the `zenoh_data_plane` flag is on. Methods mirror the gossipsub
    surface (subscribe / publish / recv) so the Python `Router` can treat it as
    an alternate transport backend.
    """
    def __new__(cls, listen_endpoints: typing.Optional[typing.Sequence[builtins.str]] = None, connect_endpoints: typing.Optional[typing.Sequence[builtins.str]] = None, namespace: typing.Optional[builtins.str] = None, multicast_scouting: builtins.bool = False) -> ZenohHandle: ...
    async def listen_addresses(self) -> builtins.list[builtins.str]:
        r"""
        Return actual bound data-plane locators without changing connectivity.
        """
    async def zenoh_subscribe(self, topic: builtins.str) -> None:
        r"""
        Subscribe to a Zenoh key (topic). Idempotent.
        """
    async def zenoh_publish(self, topic: builtins.str, data: bytes) -> None:
        r"""
        Publish `data` on a Zenoh key (Reliable + Block + single priority).
        """
    async def zenoh_connected_peer_count(self) -> builtins.int:
        r"""
        Count the Zenoh peers this session currently holds a live transport to.

        Zero while cluster peers advertise Zenoh means this node's data plane
        is isolated (its remote streams will fail) even though the libp2p
        control plane is healthy; Python advertises the count so cluster
        health can say so instead of streams dying silently.
        """
    async def recv(self) -> ZenohMessage: ...

@typing.final
class ZenohMessage:
    r"""
    One inbound Zenoh sample handed to Python: the key (topic) it arrived on and
    its raw payload. Mirrors the `Message` arm of [`PyFromSwarm`]; the data-plane
    consumer demuxes by the `command_id` carried inside `data`.
    """
    @property
    def topic(self) -> builtins.str: ...
    @property
    def data(self) -> bytes: ...
